### PR TITLE
🛩️  🏁  Removes the template specification process and cleans up template class 🐰 

### LINKED ISSUE #186: Change template specification to footprint specification
## Describe the bug
I shouldn't have to specify a template before I specify a plaquette.

## Steps to reproduce the behavior:
1. Specify unit cell
1. I must specify template, when I should be able to specify a plaquette right away.

## Expected behavior
Once the qubits have populated, I should be able to start clicking them and when 3+ have been clicked, specify a plaquette.

## Screenshots and MP4s
image

## Other context:
From discussions with @afowler .

## Coding task

Bypass the `template` functions: hoist plaquette addition into the control flow function.

### PR DESCRIPTION
**Pull request by rryoung98**
Closes #186

### CODE REVIEW

**Comment by smburdick** [comment]
Thanks @rryoung98 . This is exactly what I had in mind when we last spoke.

Per this morning's discussion, we'll want to be able to produce "plaquette footprints," which aren't the same as plaquette templates per se, hence why we needed to change the frontend to reflect that.

I think it would be nice to have the ability to specify the plaquette footprint using the infrastructure that exists within the `Template` class, which we can then rename.

To summarize, the workflow would look like:

Unit cell -> specify footprint (using click-and-drag) ->  specify circuit on plaquette, based on the footprint.

Additionally, once a footprint has been specified, we could be able to choose it from the library. Task #189 will provide the infrastructure for the library, which can include footprints, completed circuits, and scalable templates.

@afowler Do you have any more questions/commentary here? In particular, how would we define a template, now that we have footprints defined?

File: frontend/src/plaquettes/Template.js [hunk 1]
```diff
@@ -1,230 +1,87 @@
...
-    });
-    this.container.addChild(this.templateButton);
-    this.container.addChild(this.plaquetteButton);
     this.container.name = 'template';
-    // this.workspace.addChild(this.container);
+    this.initializeTemplate();
   }
 
-  // Render the template control buttons
-  renderTemplateControlButtons() {
```
Comment (smburdick) [inline frontend/src/plaquettes/Template.js:43]: We can still keep this functionality. That goes for most of the deleted code here

File: frontend/src/plaquettes/Template.js [hunk 2]
```diff
@@ -1,230 +1,87 @@
...
+/**
+ * Template class to create the template for the plaquettes
+ * @class Template
+ * @param {Container} workspace - The workspace container
+ * @param {PIXI.Application} app - The PIXI application
+ * @param {number} x - The x coordinate
+ * @param {number} y - The y coordinate
+ * @returns {void}
+ */
 export default class Template {
```
Comment (smburdick) [inline frontend/src/plaquettes/Template.js:15]: rename to `class Footprint`.

File: frontend/src/plaquettes/Template.js [hunk 3]
```diff
@@ -1,230 +1,87 @@
...
+   * @returns {void}
+   */
+  initializeTemplate = () => {
+    // Create the plaquettes and template
+    this.selectQubitsButton.on('click', () => {
       this.app.view.addEventListener('click', this.selectQubit);
-      this.plaquetteButton.visible = true;
-      this.plaquetteButton.on('click', () => {
-        // Create the plaquettes and tile
-        this.createPlaquette();
```
Comment (smburdick) [inline frontend/src/plaquettes/Template.js:109]: Footprint can still create a plaquette on top of it. In fact, I'm not sure I fully understand the difference between plaquettes and footprints at this point. @afowler Do you have any ideas?

**Comment by afowler** [comment]
For the moment they should be only one footprint for everything. For the
moment we don't plan to combine plaquettes with different footprints in a
single circuit.

File: frontend/src/plaquettes/Template.js [hunk 4]
```diff
@@ -247,14 +104,22 @@ export default class Template {
...
       // Show the button
-      this.plaquetteButton.visible = true;
+      this.selectQubitsButton.visible = false;
+      this.createPlaquetteButton.visible = true;
     }
   };
 
-  // Create the plaquette from the selected qubits and assign it to the template
+  /**
+   * Create the plaquette from the selected qubits and assign it to the template
```
Comment (smburdick) [inline frontend/src/plaquettes/Template.js:119]: assign it to the `Footprint`? Again, I still need to understand the difference.

File: frontend/src/plaquettes/Template.js [hunk 5]
```diff
@@ -263,13 +128,9 @@ export default class Template {
     }
     // Render the plaquette
     const plaquette = new Plaquette(this.selectedQubits, this.workspace, this.app);
-    // Remove seleected qubits from the template qubits, so they can be
```
Comment (smburdick) [inline frontend/src/plaquettes/Template.js:266]: To be clear, I don't think a `Footprint` should remember the specific set of qubits (in the viewport) used to create it, but should remember a cell of qubit positions (just like the unit cell) for re-creating the footprint anywhere on the viewport. Can we add that to this class?

File: frontend/src/plaquettes/Template.js [hunk 6]
```diff
@@ -1,230 +1,87 @@
...
     this.mode = 'static';
     this.isDragging = false;
+    this.x = x;
+    this.y = y;
     this.startX = 0;
     this.startY = 0;
     this.plaquette = null;
-    this.plaquetteButton = plaquetteButton;
-    this.templateQubits = selectedQubits || [];
+    this.selectQubitsButton = new Button('Select 3 qubits to make a Plaquette', x, y + 50);
```
Comment (smburdick) [inline frontend/src/plaquettes/Template.js:29]: Before this point, qubits should not be clickable (when my mouse hovers over them, the Mickey Mouse hand should not appear). Can we change that?

Comment (smburdick) [reply frontend/src/plaquettes/Template.js:29]: Also, it should say "Select 3+ qubits to make a Plaquette Footprint"

File: frontend/src/plaquettes/Template.js [hunk 7]
```diff
@@ -1,230 +1,87 @@
...
-        this.createPlaquette();
-        this.workspace.addChild(this.container);
-        // Clear the selected qubits
-        this.selectedQubits = [];
-        notification(this.app, 'Step 4: Define the circuit');
+      this.unselectQubitsButton.visible = true;
+      this.selectQubitsButton.visible = false;
+      this.createPlaquetteButton.visible = false;
+    });
+    this.unselectQubitsButton.on('click', () => {
```
Comment (smburdick) [inline frontend/src/plaquettes/Template.js:52]: Nice. I'm planning on adding undo/redo buttons in general (for the whole app), but this is good to have until that's implemented.

**Review by smburdick — CHANGES_REQUESTED** [review]
Looks good overall, but making some suggestions based on this morning's meeting.

**Comment by smburdick** [comment]
> For the moment they should be only one footprint for everything. For the moment we don't plan to combine plaquettes with different footprints in a single circuit.

@afowler OK, we can leave footprint specification as-is then. I'll add plaquette footprint saving/specification to the next milestone.

**Comment by afowler** [comment]
The best example of the difference between a footprint and a plaquette is
our usual architecture and a memory surface code. The footprint of every
plaquette will be a square including 5 qubits. The plaquette itself, and
it's shape symbol, will fit inside this footprint, and could be a subset,
for example a triangle that attaches to the bottom, top, right, or left of
the footprint. Every plaquette should have the same footprint so that
plaquettes connect neatly when inserted into templates which are just
integer arrays.

Does this clarify the need for a footprint?

**Comment by smburdick** [comment]
>  could be a subset, for example a triangle that attaches to the bottom, top, right, or left of the footprint.

@afowler That makes sense, but would the triangular plaquette still be something we want in the plaquette library? What would the use case for creating one be? I think the purpose of the library would be to have different *circuits*.

File: frontend/src/plaquettes/Template.js (hunk 1 above)
Comment (rryoung98) [reply frontend/src/plaquettes/Template.js:43]: do we want to leave it uncommented?

File: frontend/src/plaquettes/Template.js (hunk 4 above)
Comment (rryoung98) [reply frontend/src/plaquettes/Template.js]: Not sure what you mean here....I have made the name change though :)

File: frontend/src/plaquettes/Template.js (hunk 5 above)
Comment (rryoung98) [reply frontend/src/plaquettes/Template.js:266]: yes, would you mind pointing me to how we are instantiating the qubit positions?

File: frontend/src/plaquettes/Template.js (hunk 6 above)
Comment (rryoung98) [reply frontend/src/plaquettes/Template.js]: Done

Comment (rryoung98) [reply frontend/src/plaquettes/Template.js]: the clicking functionality resides in the qubit class and we can do it in a separate issue.

File: frontend/src/plaquettes/Template.js (hunk 1 above)
Comment (smburdick) [reply frontend/src/plaquettes/Template.js:43]: Yes. If it's not being invoked at the moment, it should remain uncommented.

File: frontend/src/plaquettes/Template.js (hunk 4 above)
Comment (smburdick) [reply frontend/src/plaquettes/Template.js]: The notion of a plaquette is different from a plaquette footprint, and the goal of the name change is to make that clear. We should discuss in the meeting, I think.

File: frontend/src/plaquettes/Template.js (hunk 5 above)
Comment (smburdick) [reply frontend/src/plaquettes/Template.js:266]: When it is placed, that information should be known to the workspace. When it is stored (say, in redux), we only need to store the *relative* positions. There's a 1-1 correspondence, and storing relative positions helps us keep things general.

Comment (rryoung98) [reply frontend/src/plaquettes/Template.js:266]: Okay makes sense, w.r.t. relative position could you point me towards any existing code that lays out the foundation?

File: frontend/src/plaquettes/Template.js (hunk 4 above)
Comment (rryoung98) [reply frontend/src/plaquettes/Template.js]: That's clear to me. I wasn't sure if you were commenting on the edit from single line comment to multiline

File: frontend/src/plaquettes/Template.js (hunk 1 above)
Comment (rryoung98) [reply frontend/src/plaquettes/Template.js:43]: added it back

File: frontend/src/plaquettes/Template.js (hunk 4 above)
Comment (smburdick) [reply frontend/src/plaquettes/Template.js]: I'm saying it should say `assign it to the footprint`

**Comment by smburdick** [comment]
@rryoung98 Is this ready for re-review?

**Comment by rryoung98** [comment]
@smburdick i haven't done the relative positioning since the frontend version 2, if i recall might already have the relative positioning notion. Otherwise, it's all set for re-review

**Comment by smburdick** [comment]
> @smburdick i haven't done the relative positioning since the frontend version 2, if i recall might already have the relative positioning notion. Otherwise, it's all set for re-review

Thanks, and in the future, be sure to request that from the reviewer when ready.

File: frontend/src/plaquettes/Footprint.js [hunk 8]
```diff
@@ -3,123 +3,194 @@ import Plaquette from './Plaquette';
...
+    const relativeY = e.clientY - canvasRect.top;
+    // Get all the qubits
+    const qubits = this.workspace.children.filter(
+      (child) => child.isQubit === true
+    );
+    const qubit = qubits.find(
+      // Find the qubit that was clicked
+      (q) => q.checkHitArea(relativeX, relativeY) === true
+    );
+    if (!qubit && !(qubit?.isQubit === true)) return; // Check that the qubit exists
```
Comment (smburdick) [inline frontend/src/plaquettes/Footprint.js:101]: `qubit.isQubit` should be deprecated, since a qubit is always a qubit; perhaps you meant to check its visibility?

File: frontend/src/plaquettes/Footprint.js [hunk 9]
```diff
@@ -3,123 +3,194 @@ import Plaquette from './Plaquette';
...
+    this.createPlaquetteButton.visible = false;
+    this.unselectQubitsButton.visible = false;
+  };
+
+  /**
+   * Render the footprint
+   * @function renderFootprintControlButtons
+   * @returns {void}
+   */
+  renderFootprintControlButtons() {
```
Comment (smburdick) [inline frontend/src/plaquettes/Footprint.js:153]: A better name would be something like `updateVisiblityAndEventListeners()` since rendering is not the job of a `Container` per se

**Review by smburdick — COMMENTED** [review]
Minor comments.

File: frontend/src/plaquettes/Footprint.js (hunk 8 above)
Comment (rryoung98) [reply frontend/src/plaquettes/Footprint.js:101]: This is a built in for the QubitClass since it's a convenient way to check if child components, such as graphics or containers are indeed representing a qubit. Without the .isQubit state, it would be difficult to filter through a set of child containers and determine if its a qubit or not.

Comment (smburdick) [reply frontend/src/plaquettes/Footprint.js:101]: In that case, you should use `instanceof Qubit`.

Comment (rryoung98) [reply frontend/src/plaquettes/Footprint.js:101]: sounds good! thanks

**Comment by rryoung98** [comment]
@smburdick  please re-review

**Review by smburdick — APPROVED** [review]
image

I think we should remove this label as a button, since I don't have to actually click it to make a new footprint -- I can still make plaquettes by clicking on qubits, and clicking "create plaquette". So, instead of having the button, we can simply add the text to the topbar.

Looks good otherwise, you can make the changes here, or create a new issue to address that.

**Comment by rryoung98** [comment]
> image
> I think we should remove this label as a button, since I don't have to actually click it to make a new footprint -- I can still make plaquettes by clicking on qubits, and clicking "create plaquette". So, instead of having the button, we can simply add the text to the topbar.
> 
> Looks good otherwise, you can make the changes here, or create a new issue to address that.

Done
